name: PlayConsultant
version: '${version}'

main: eu.bruza.vojtech.playConsultantPlugin.PlayConsultantPlugin
api-version: '1.21.4'
load: POSTWORLD

authors: [ Vojtech Bruza ]

commands:
  playconsultant:
    description: Main command for PlayConsultant. Use subcommands for specific actions.
    aliases: [pc]

depend: [DecentHolograms, PlotSquared, FastAsyncWorldEdit]

permissions:
  playconsultant.removecomment:
    description: Allows removing nearby comments
    default: op
  playconsultant.reloadconfig:
    description: Allows reloading the plugin configuration
    default: op
  playconsultant.resetplayerdata:
    description: Allows resetting player data
    default: op