name: PlayConsultantPlugin
version: '${version}'

main: eu.bruza.vojtech.playConsultantPlugin.PlayConsultantPlugin
api-version: '1.21.4'
load: POSTWORLD

authors: [ Vojtech Bruza ]

commands:
  megaphone:
    description: Gives the player a megaphone.

depend: [DecentHolograms]